import { Hono } from 'hono';
import chamados from './chamados';
import chamadosRecorrentes from './chamados-recorrentes';
import categorias from './categorias';
import grupos from './grupos';
import slas from './slas';
import projetos from './projetos';
import contratos from './contratos';
import ativos from './ativos';
import setores from './setores';
import estoque from './estoque';
import whatsapp from './whatsapp';
import metaWhatsapp from './meta-whatsapp';
import gamificacao from './gamificacao';
import treinamentos from './treinamentos';
import badges from './badges';
import manutencoesPreventivas from './manutencoes-preventivas';
import filas from './filas';
import diagnosticoChamados from './diagnostico-chamados';
import diagnosticoSetores from './diagnostico-setores';
import userSetoresAcesso from './user-setores-acesso';
import relatorioTickets from './relatorio-tickets';
import relatorioSetores from './relatorio-setores';
import fixCategoriasTelegram from './fix-categorias-telegram';
import fixSlaTelegram from './fix-sla-telegram';
import fixSlaReabertoMv from './fix-sla-reaberto-mv';
import fixSetorRecorrente from './fix-setor-recorrente';
import analiseSla from './analise-sla';
import limparPrazoResposta from './limpar-prazo-resposta';
import fixManutencaoTi from './fix-manutencao-ti';
import avaliacoesPendentes from './avaliacoes-pendentes';
import corrigirSlaPausado from './corrigir-sla-pausado';
import diagnosticoTicket from './diagnostico-ticket';
import corrigirSlaSetores from './corrigir-sla-setores';
import diagnosticoProducao from './diagnostico-producao';

const router = new Hono<{ Bindings: Env }>();

router.route('/chamados', chamados);
router.route('/chamados-recorrentes', chamadosRecorrentes);
router.route('/categorias', categorias);
router.route('/grupos', grupos);
router.route('/slas', slas);
router.route('/projetos', projetos);
router.route('/contratos', contratos);
router.route('/ativos', ativos);
router.route('/setores', setores);
router.route('/estoque', estoque);
router.route('/whatsapp', whatsapp);
router.route('/meta-whatsapp', metaWhatsapp);
router.route('/gamificacao', gamificacao);
router.route('/treinamentos', treinamentos);
router.route('/badges', badges);
router.route('/manutencoes-preventivas', manutencoesPreventivas);
router.route('/filas', filas);
router.route('/diagnostico-chamados', diagnosticoChamados);
router.route('/diagnostico-setores', diagnosticoSetores);
router.route('/user-setores-acesso', userSetoresAcesso);
router.route('/relatorio-tickets', relatorioTickets);
router.route('/relatorio-setores', relatorioSetores);
router.route('/fix-categorias-telegram', fixCategoriasTelegram);
router.route('/fix-sla-telegram', fixSlaTelegram);
router.route('/fix-sla-reaberto-mv', fixSlaReabertoMv);
router.route('/fix-setor-recorrente', fixSetorRecorrente);
router.route('/analise-sla', analiseSla);
router.route('/limpar-prazo-resposta', limparPrazoResposta);
router.route('/fix-manutencao-ti', fixManutencaoTi);
router.route('/avaliacoes-pendentes', avaliacoesPendentes);
router.route('/corrigir-sla-pausado', corrigirSlaPausado);
router.route('/diagnostico-ticket', diagnosticoTicket);
router.route('/corrigir-sla-setores', corrigirSlaSetores);
router.route('/diagnostico-producao', diagnosticoProducao);

export default router;
